apiVersion: v1
kind: Pod
metadata:
  name: mysql-db-pod
  labels:
    env: testing
    region: IN
spec:
   containers:
    - name: mysql-db-con
      image: mysql:5.7
      env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mysql-db-secure
           key: rootpass
       - name: MYSQL_USER
         value: nitin
       - name: MYSQL_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mysql-db-secure
           key: userpass
       - name: MYSQL_DATABASE
         value: mydb
      volumeMounts:
       - name: mysql-db-vol
         mountPath: /var/lib/mysql
   volumes:
    - name: mysql-db-vol
      persistentVolumeClaim:
       claimName: mysql-db-pvc
  