--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  name: myweb-rc
spec: 
  replicas: 7
  selector: 
    env: production
  template: 
    metadata: 
      labels: 
        env: production
      name: myweb-pod
    spec: 
      containers: 
        - 
          image: httpd
          name: myweb-con
